# Setup
title:        Niklas Inde
tagline:      Everything i may or may not need in the future
baseurl:
paginate:     1

# About/contact
author:       Niklas Inde
  name:       
  url:        https://niklasinde.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
kramdown:
  math_engine: mathjax
