# Setup
title:        Project or Site name
tagline:      Everything i may or may not need in the future
baseurl:      "niklasinde.github.io"
paginate:     1

# About/contact
author:
  name:       Niklas Inde
  url:        http://niklasinde.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
